apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-deployment
  labels:
    app: webgoat
spec:
  replicas: 3
  selector:
    matchLabels
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
      - name: webgoat
        image: your_docker_hub_username/webgoat:latest
        ports:
        - containerPort: 8080
